project:
  type: website
  output-dir: docs

website:
  title: "To Test, or Not to Test?"
  navbar:
    left:
      - href: index.qmd
        text: Report
      - href: data\data_cleaning.ipynb
        text: Data Cleaning and AI Statement

format:
  html:
    df-print: kable
  pdf: default
  # docx: default
  jats: default

execute:
  freeze: true



